CREATE TABLE IF NOT EXISTS difficulties (
--     ID
    id_diff INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     ID пользователя
    threshold FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS posts (
--     ID
    id_post INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     Название
    name VARCHAR(50) NOT NULL,
--     Описание
    description VARCHAR(500) NOT NULL,
    diff_id INT NOT NULL,

    FOREIGN KEY(diff_id) REFERENCES difficulties(id_diff)
);

CREATE TABLE IF NOT EXISTS test_questions (
--     ID вопроса
    id_question  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     Текст вопроса
    text VARCHAR(500) NOT NULL,
--     Варианты ответа
    answer_option1 VARCHAR(500) NOT NULL,
    answer_accuracy1 BOOLEAN NOT NULL,
    answer_option2 VARCHAR(500) NOT NULL,
    answer_accuracy2 BOOLEAN NOT NULL,
    answer_option3 VARCHAR(500) NOT NULL,
    answer_accuracy3 BOOLEAN NOT NULL,
    answer_option4 VARCHAR(500) NOT NULL,
    answer_accuracy4 BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS post_question_map (
    post_id INT NOT NULL,
    question_id INT NOT NULL,
    PRIMARY KEY(post_id, question_id),

    FOREIGN KEY(post_id) REFERENCES posts(id_post),
    FOREIGN KEY(question_id) REFERENCES test_questions(id_question)
);
