CREATE TABLE IF NOT EXISTS roles (
--     ID
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(500) NOT NULL,
    created_at DATE,
    updated_at DATE
);

CREATE TABLE IF NOT EXISTS users (
--     ID
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    role_id INT NOT NULL,
    post_id INT NOT NULL,

    FOREIGN KEY(role_id) REFERENCES roles(id),
    FOREIGN KEY(post_id) REFERENCES posts(id_post)
);

CREATE TABLE IF NOT EXISTS tests (
--     ID теста
    id_test  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     ID пользователя
    user_id INT NOT NULL,
----     ID сложности
--    diff_id INT NOT NULL,
--     статус
    status_id INT NOT NULL,
--     результат
    result FLOAT,
--     итог (прошёл/не прошёл)
    success BOOLEAN,
    pass_date DATE,

--    FOREIGN KEY(diff_id) REFERENCES difficulties(id_diff),
    FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS test_user_responses (
----     ID ответа
--    id_answer INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
----     ID пользователя
--    user_id INT NOT NULL,
--     ID теста
    test_id INT NOT NULL,
--     ID вопроса
    question_id INT NOT NULL,
--     Ответы пользователя
    user_response1 BOOLEAN NOT NULL,
    user_response2 BOOLEAN NOT NULL,
    user_response3 BOOLEAN NOT NULL,
    user_response4 BOOLEAN NOT NULL,

    PRIMARY KEY(test_id, question_id),

    FOREIGN KEY(question_id) REFERENCES test_questions(id_question),
    FOREIGN KEY(test_id) REFERENCES tests(id_test)
);